# Generated by Django 3.2.6 on 2021-08-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210823_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_seller',
        ),
    ]
