# Generated by Django 3.2.6 on 2021-08-24 09:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210824_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('seller', 'SELLER'), ('customer', 'CUSTOMER')], default=[], max_length=15, null=True),
        ),
    ]
