# Generated by Django 3.2.6 on 2021-08-28 07:37

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customeradditional_selleradditional'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('seller', 'SELLER'), ('customer', 'CUSTOMER')], default=[], max_length=15, null=True),
        ),
    ]
